### ISSUE TITLE
[New core request] CPPM (combined PPM) decoder

### ISSUE THREAD

**Issue by qbit-** [Guzunty/Pi#14]
Hi everybody here!
I'm very new to CPLD programming, but already impressed by the range of things one can do with it. I wonder if it's possible to design a Pulse Position Modulation decoder with Gizunty? This type of signal encoding is increasingly used by modern RC systems. For an example of what it is one can consider this article:
http://diydrones.com/profiles/blog/show?id=705844%3ABlogPost%3A984615&commentId=705844%3AComment%3A987491&xg_source=activity
or just have a look at the figure:
![scheme](https://f.cloud.github.com/assets/4794088/713288/d512fb64-dec2-11e2-9dd2-b0a9a2bb7671.jpg)
Shortly speaking this signal is a sum of some number of PWM signals. It has a falling edge each time a PWM has a rising edge.
By decoding CPPM I mean that CPLD should emit a stream of numbers corresponding to each pulse length through SPI. If such an encoder could be created it will greatly simplify the use of Raspberry Pi and Gizunty by all RC people :)

**Comment by campbellsan** [comment]
I'm pleased to say that I have finally been able to justify purchase of hardware to enable this core to be tested. Just as well too, the CPPM signal coming out of the receiver is not clean and must be debounced.

Since the core is now working and meets all of the design goals I'm closing this issue.
